### ISSUE TITLE
Let us create conflicts and resolve !!!

### ISSUE THREAD

**Issue by Divyasf-gh** [Divyasf-gh/GITDEMOWU#2]
I will start modifying the "CreateAccountTest" class. Please work on the same...

**Comment by DemoGH16** [comment]
Ok..i will also work on the same

**Comment by DemoGH16** [comment]
Can i push my changes to remote?

**Comment by Divyasf-gh** [comment]
yes u can push

**Comment by DemoGH16** [comment]
Ok

**Comment by DemoGH16** [comment]
Done

**Comment by Divyasf-gh** [comment]
successfull  :)
